export { nutritionConfig } from './config'
export { proposeAdjustments } from './adjustments'
export { proposeGutTraining } from './gut'
export { clamp, isFiniteNumber, lookupFactor, roundTo } from './math'
export { buildPlan, buildSegments } from './planner'
export type { PlanRequest } from './planner'
export { computeTargets, presetTriathlon, resolveEvent } from './targets'
export { formatMinute, formatPlanText } from './text'
export * from './types'
